### ISSUE TITLE
Non-boss Octopus

### ISSUE THREAD

**Issue by AndreMoukarzel** [uspgamedev/welcome-to-your-mind#17]
Should follow Player after entering its puzzle room and shoot TriggerWaves at it.

**Comment by rilifon** [comment]
Who doesn't love TriggerWaves for breakfast

Em Qua, 24 de out de 2018 02:56, Andre Ferrari Moukarzel <
notifications@github.com escreveu:

**Comment by AndreMoukarzel** [comment]
> Who doesn't love TriggerWaves for breakfast 

https://media.tenor.com/images/53894fc7270048ca3870311ebb3bcef5/tenor.gif

**Comment by AndreMoukarzel** [comment]
commit 38e47b2
